### ISSUE TITLE
About menu open url with default browser failed

### ISSUE THREAD

**Issue by lennylxx** [shadowsocks/shadowsocks-csharp#215]
**Information**:
Version: Shadowsocks win dotnet4.0 2.3.1
OS: Windows 8.1 Pro 64-bit with English language pack
Default Browser: Chrome 40.0.2214.115 m (64-bit)
Other Browser: Internet Explorer 11.0.9600.17690

**How to reproduce**:
Make Internet Explorer the default browser, it works fine.
Start Chrome and set it as the default browser, Win32Exception raises.

**Full Exception message**:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): Class not registered
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Shadowsocks.View.MenuViewController.AboutItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Command.DispatchID(Int32 id)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Shadowsocks
    Assembly Version: 2.3.1.0
    Win32 Version: 2.3.1.0
    CodeBase: file:///D:/Software/Shadowsocks/Shadowsocks.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34239 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Potential solution**:
As Win32Exception was unhandled, with specific version of Google Chrome, shadowsocks will crash due to wrong path of the current default browser.
A new "Default Programs" registry key was introduced in Windows Vista and newer versions of Windows, it is saved under the following:
```
HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice\Progid
```
In my case the `Progid` is `ChromeHTML`, and the correct path of default browser is under:
```
HKEY_CLASSES_ROOT\ChromeHTML\shell\open\command 
```

**References**:
https://support.microsoft.com/en-us/kb/305703
http://www.seirer.net/blog/2014/6/10/solved-how-to-open-a-url-in-the-default-browser-in-csharp
http://stackoverflow.com/questions/13621467/how-to-find-default-web-browser-using-c

**Comment by clowwindy** [comment]
I believe this exception has something to do with UAC on Windows 8.1: http://stackoverflow.com/questions/502199/how-to-open-a-web-page-from-my-application

**Comment by lennylxx** [comment]
Link above says that it will raise a exception if you launch a web page in an elevated application. 
However, according to the manifest file, shadowsocks-csharp isn't elevated.

      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
        <requestedExecutionLevel level="asInvoker" uiAccess="false" />
      </requestedPrivileges>

**Comment by clowwindy** [comment]
It's weird to take so many lines of code just to open an URL. If the recommended Process.Start() doesn't work, it should be considered as a bug of Windows or Chrome.

**Comment by lennylxx** [comment]
All right. You are the boss, it's your call. :smirk:

**Comment by clowwindy** [comment]
Thanks anyway :)
